// Generated by CoffeeScript 1.7.1
(function() {
  define(['todo-list/section'], function(Section) {
    'use strict';
    var Container;
    Container = (function() {
      function Container() {
        this.sections = [];
      }

      Container.prototype.add = function(section) {
        if (!(section instanceof Section)) {
          throw {
            message: 'Trying to add non-Section object to Container'
          };
        }
        this.sections.push(section);
        return this;
      };

      Container.prototype.getData = function() {
        var dataSections, section;
        return dataSections = (function() {
          var _i, _len, _ref, _results;
          _ref = this.sections;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            section = _ref[_i];
            _results.push(section.getData());
          }
          return _results;
        }).call(this);
      };

      return Container;

    })();
    return Container;
  });

}).call(this);

//# sourceMappingURL=container.map
