// Generated by CoffeeScript 1.7.1
(function() {
  define(['todo-list/item'], function(Item) {
    'use strict';
    var Section;
    Section = (function() {
      function Section(title) {
        this.title = title;
        this.items = [];
      }

      Section.prototype.add = function(item) {
        if (!(item instanceof Item)) {
          throw {
            message: 'Trying to add non-Item item to a section'
          };
        }
        this.items.push(item);
        return this;
      };

      Section.prototype.getData = function() {
        var dataItems, item;
        dataItems = (function() {
          var _i, _len, _ref, _results;
          _ref = this.items;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            item = _ref[_i];
            _results.push(item.getData());
          }
          return _results;
        }).call(this);
        return {
          title: this.title,
          items: dataItems
        };
      };

      return Section;

    })();
    return Section;
  });

}).call(this);

//# sourceMappingURL=section.map
