// Generated by CoffeeScript 1.7.1
(function() {
  define(function() {
    var Student;
    return Student = (function() {
      function Student(params) {
        this.name = params.name, this.exam = params.exam, this.homework = params.homework, this.attendance = params.attendance, this.teamwork = params.teamwork, this.bonus = params.bonus;
      }

      return Student;

    })();
  });

}).call(this);

//# sourceMappingURL=student.map
