//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringContainsService.Client.StringContainsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StringContainsServiceReference.IStringContainsService")]
    public interface IStringContainsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringContainsService/GetNumberOccurrences", ReplyAction="http://tempuri.org/IStringContainsService/GetNumberOccurrencesResponse")]
        int GetNumberOccurrences(string stringToSearchIn, string stringToFind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringContainsService/GetNumberOccurrences", ReplyAction="http://tempuri.org/IStringContainsService/GetNumberOccurrencesResponse")]
        System.Threading.Tasks.Task<int> GetNumberOccurrencesAsync(string stringToSearchIn, string stringToFind);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringContainsServiceChannel : StringContainsService.Client.StringContainsServiceReference.IStringContainsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringContainsServiceClient : System.ServiceModel.ClientBase<StringContainsService.Client.StringContainsServiceReference.IStringContainsService>, StringContainsService.Client.StringContainsServiceReference.IStringContainsService {
        
        public StringContainsServiceClient() {
        }
        
        public StringContainsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringContainsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringContainsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringContainsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetNumberOccurrences(string stringToSearchIn, string stringToFind) {
            return base.Channel.GetNumberOccurrences(stringToSearchIn, stringToFind);
        }
        
        public System.Threading.Tasks.Task<int> GetNumberOccurrencesAsync(string stringToSearchIn, string stringToFind) {
            return base.Channel.GetNumberOccurrencesAsync(stringToSearchIn, stringToFind);
        }
    }
}
